package rules;

import com.united.drools.entity.Customer;
import com.united.drools.utilities.PreChecks;

dialect "java"

rule "Is user gold citizen?"
    when
        thisCustomer : Customer ();
    then
        //thisCustomer.setCategory(PreChecks.checkOffer(thisCustomer.age));
        thisCustomer.setCategory("Gold");
        //$offer : PreChecks.isEligible(30);
        //System.out.println("In rule ->"+$offer);
end;